[versions]
"spring-boot" = "4.0.6"
"spring-dependency-management" = "1.1.7"
"postgresql" = "42.7.11"
"lombok" = "1.18.46"

[libraries]
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter", version.ref = "spring-boot" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "spring-boot" }
spring-boot-starter-webmvc = { module = "org.springframework.boot:spring-boot-starter-webmvc", version.ref = "spring-boot" }
spring-boot-starter-thymeleaf = { module = "org.springframework.boot:spring-boot-starter-thymeleaf", version.ref = "spring-boot" }
spring-boot-starter-webmvc-test = { module = "org.springframework.boot:spring-boot-starter-webmvc-test", version.ref = "spring-boot" }
spring-boot-starter-thymeleaf-test= { module = "org.springframework.boot:spring-boot-starter-thymeleaf-test", version.ref = "spring-boot" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation", version.ref = "spring-boot" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security", version.ref = "spring-boot" }

spring-boot-docker-compose = { module = "org.springframework.boot:spring-boot-docker-compose", version.ref = "spring-boot" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa", version.ref = "spring-boot" }
spring-boot-dev-tools = { module = "org.springframework.boot:spring-boot-devtools", version.ref = "spring-boot" }
postgresql-jdbc-driver = { module = "org.postgresql:postgresql", version.ref="postgresql" }
project-lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }

[bundles]
spring-boot-web = [ "spring-boot-starter-webmvc", "spring-boot-starter-thymeleaf", "spring-boot-starter-validation", "spring-boot-starter-security" ]
spring-boot-web-test = [ "spring-boot-starter-webmvc-test", "spring-boot-starter-thymeleaf-test" ]
spring-boot-application = [ "spring-boot-starter", "spring-boot-starter-validation", "spring-boot-starter-data-jpa", "spring-boot-starter-security" ]
spring-boot-application-test = [ "spring-boot-starter-test" ]