spring.thymeleaf.cache=false

spring.security.remember-me-key=${REMEMBER_ME_KEY:development_profile_key}

spring.docker.compose.file=docker-compose.dev.yaml

spring.datasource.url=jdbc:postgresql://localhost:5432/glacial_db
spring.datasource.username=glacial_user
spring.datasource.password=glacial_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:database/schema.sql
spring.sql.init.data-locations=classpath:database/data.sql
spring.jpa.defer-datasource-initialization=true

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

logging.level.org.hibernate.engine.transaction.jta.platform=WARN